#!/bin/sh

N=2
RESOURCE_DIR=resource
EXECUTE_FILE_FORMAT="./test%02u.exe"
OUTPUT_FILE_FORMAT="out%02u.txt"
ANSWER_FILE_FORMAT="${RESOURCE_DIR}/ans%02u.txt"

for i in `seq 1 $N` ;
do
	exe=`printf ${EXECUTE_FILE_FORMAT} $i`
	out=`printf ${OUTPUT_FILE_FORMAT}  $i`
	ans=`printf ${ANSWER_FILE_FORMAT}  $i`
	${exe} > ${out}
	diff ${out} ${ans}
	rm ${out}
done
